import Head from "next/head";

import Header from "./Componentes/Header/header";
import BannerSorvete from "./banner_sorvete/Banner_sorvete";
import Nossos_eventos from "./Nossos_eventos/nossos_eventos";
import Rodape from "./Componentes/Roda_pe/footer";


export default function Home(){
  return(
    <>
    <Head>
     <meta name="description" content="Generated by create next app" />
     <meta name="viewport" content="width=device-width, initial-scale=1" />
     <link rel="icon" href="sorvete_icon.png"/> 
     </Head>
     <Header/>
     <BannerSorvete/>
     <Nossos_eventos/>
     <Rodape/>
    </>
  )
}
